apiVersion: external-secrets.io/v1beta1
{{- if .Values.isClusterSecretStore }}
kind: ClusterSecretStore
{{- else }}
kind: SecretStore
{{- end }}
metadata:
  name: vault-backend
  {{- if .Values.isClusterSecretStore }}
  namespace: external-secrets
  {{- else }}
  namespace: default
  {{- end }}
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200" # Calling local vault running in same cluster
      path: "ingress"
      version: "v2"
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: "{{ .Values.roleID }}"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "vault-secret"
            key: "secret-id"
