apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-storage-pv-0
  labels:
    app: my-app
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: "/tmp/shared-data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-storage-pv-1
  labels:
    app: my-app
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: "/tmp/shared-data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-storage-pv-2
  labels:
    app: my-app
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: "/tmp/shared-data"
