apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pki-external-secret
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: my-secret
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: ingress/my-app.mitkar.io
        property: ca.crt
    - secretKey: tls.crt
      remoteRef:
        key: ingress/my-app.mitkar.io
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: ingress/my-app.mitkar.io
        property: tls.key
