apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-pki-renew
  namespace: default
spec:
  schedule: "0 0 * * *"  # Runs daily at midnight
  #schedule: "* * * * *"  # Runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: vault-access
          restartPolicy: OnFailure
          containers:
            - name: cert-renewal
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - "-c"
                - |
                  echo "Fetching new certificate from Vault..."

                  VAULT_ADDR="http://vault.vault.svc.cluster.local:8200"
                  VAULT_TOKEN=$(kubectl get secret vault-token -n vault -o jsonpath="{.data.token}" | base64 --decode)

                  CERT_OUTPUT=$(kubectl -n vault exec -it vault-0 -- vault write -format=json pki/issue/mitkar-io \
                      common_name="my-app.mitkar.io" \
                      ttl="24h" \
                      token=$VAULT_TOKEN)

                  echo "Extracting certificate..."
                  CRT=$(echo "$CERT_OUTPUT" | jq -r '.data.certificate')
                  KEY=$(echo "$CERT_OUTPUT" | jq -r '.data.private_key')
                  CA=$(echo "$CERT_OUTPUT" | jq -r '.data.issuing_ca')

                  echo "$CRT" > /tmp/tls.crt
                  echo "$KEY" > /tmp/tls.key
                  echo "$CA" > /tmp/ca.crt

                  echo "Updating Kubernetes TLS Secret..."
                  kubectl create secret tls mitkar-tls --cert=/tmp/tls.crt --key=/tmp/tls.key --dry-run=client -o yaml | kubectl apply -f -

                  echo "Certificate renewal complete!"
