apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
  namespace: default
type: Opaque
stringData:
  VAULT_ADDR: "http://vault.vault.svc:8200"
  VAULT_ROLE_ID: "08457eda-80c4-787b-7e58-6d08d36423e9" # Replace with actual Role ID
  VAULT_SECRET_ID: "c1e14301-e761-cf2a-79a4-4bbfa90e400d" # Replace with actual Secret ID
