apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "ingress"
      version: "v2"
      auth:
        appRole:
          secretRef:
            name: vault-secret
            namespace: default
            key: VAULT_SECRET_ID
          roleId: "08457eda-80c4-787b-7e58-6d08d36423e9"  # Replace with actual Role ID
