apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
  namespace: default
type: Opaque
stringData:
  VAULT_ADDR: "http://vault.vault.svc:8200"
  VAULT_ROLE_ID: "{{ .Values.roleID }}" # Replace with actual Role ID
  VAULT_SECRET_ID: "{{ .Values.secretID }}" # Replace with actual Secret ID
